<a href="https://colab.research.google.com/github/c4ic79/ML-Basic/blob/main/%EB%82%98%EC%9D%B4%EB%B8%8C%EB%B2%A0%EC%9D%B4%EC%A6%88_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#독립변수간의 상관관계가 없음을 가정
#나이브베이즈분류기:데이터가 각 클래스에 속할 특징확률을 계산
#n개의 특징을 가진 샘플데이터 x개가 주어졌을때 k개의 클래스 중 하나에 속할 확률을 결정
#설명변수가 연속 ->가우시안나이브베이즈
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [6]:
import pandas as pd

In [10]:
iris=datasets.load_iris()
X=pd.DataFrame(iris.data)
Y=pd.DataFrame(iris.target)

In [11]:
X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [13]:
Y.head()

0
0  0
1  0
2  0
3  0
4  0

In [15]:
gnb=GaussianNB()
fitted=gnb.fit(X,Y)
y_pred=fitted.predict(X)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [19]:
fitted.predict_proba(X)[[1,48,51,100]] #0,1,2일 확률
fitted.predict(X)[[1,48,51,100]]

array([0, 0, 1, 2])

In [21]:
#confusion matrix : 예측성능을 측정하기 위해 예측값과 실제값을 비교하기 위한 표
from sklearn.metrics import confusion_matrix


In [31]:
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

In [33]:
#특정 결과의 출현확률이 더 많다고 가중치를 주는 행위
gnb2=GaussianNB(priors=[1/100,98/100,1/100])

fitted2=gnb2.fit(X,Y)
y_pred2=fitted2.predict(X)
confusion_matrix(iris.target,y_pred2)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]])

In [38]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np

X=np.random.randint(5,size=(6,100))
y=np.array([1,2,3,4,5,6])

In [39]:
X

array([[1, 4, 3, 3, 4, 2, 1, 2, 3, 2, 1, 3, 4, 1, 4, 0, 0, 4, 3, 2, 2, 4,
        3, 1, 1, 0, 1, 0, 2, 2, 0, 4, 0, 1, 4, 2, 4, 2, 2, 1, 2, 1, 3, 2,
        0, 0, 1, 3, 0, 4, 4, 3, 3, 2, 2, 2, 2, 0, 4, 3, 1, 2, 4, 3, 1, 2,
        0, 1, 3, 0, 3, 1, 3, 0, 3, 0, 2, 3, 1, 0, 4, 0, 3, 4, 0, 0, 2, 0,
        2, 1, 4, 2, 4, 4, 4, 4, 1, 3, 2, 1],
       [4, 4, 2, 4, 0, 4, 4, 3, 4, 0, 2, 0, 3, 4, 0, 1, 4, 0, 1, 1, 3, 0,
        1, 0, 0, 1, 2, 0, 3, 1, 1, 3, 4, 3, 4, 3, 3, 3, 3, 0, 4, 1, 1, 1,
        3, 2, 1, 1, 3, 0, 1, 0, 2, 0, 4, 0, 1, 0, 1, 3, 4, 1, 3, 1, 0, 2,
        1, 3, 0, 3, 0, 2, 4, 0, 1, 1, 2, 3, 3, 4, 2, 2, 3, 1, 2, 3, 2, 3,
        4, 2, 1, 2, 1, 4, 1, 0, 3, 2, 1, 0],
       [0, 3, 3, 3, 1, 0, 4, 2, 0, 1, 0, 4, 1, 1, 4, 3, 1, 2, 2, 0, 2, 0,
        4, 3, 1, 0, 3, 2, 1, 0, 4, 1, 2, 4, 4, 2, 4, 4, 1, 3, 3, 3, 2, 1,
        4, 3, 2, 4, 1, 3, 2, 4, 2, 1, 3, 1, 0, 2, 1, 2, 2, 4, 4, 1, 1, 4,
        2, 0, 3, 4, 4, 2, 2, 1, 4, 1, 4, 3, 3, 4, 3, 1, 4, 4, 0, 1, 0, 0,
        1, 2, 2, 0, 3,

In [40]:
y

array([1, 2, 3, 4, 5, 6])

In [42]:
clf=MultinomialNB()
clf.fit(X,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [43]:
print(clf.predict(X[1:3]))

[2 3]


In [45]:
clf.predict_proba(X[2:3])

array([[1.99678315e-28, 1.90514778e-34, 1.00000000e+00, 2.26101891e-36,
        4.74324017e-35, 9.04791988e-34]])

In [52]:
clf2=MultinomialNB(class_prior=[0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X,y)

MultinomialNB(alpha=1.0, class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1],
              fit_prior=True)

In [54]:
clf2.predict_proba(X[2:3])

array([[1.99678315e-28, 9.52573891e-34, 1.00000000e+00, 2.26101891e-36,
        4.74324017e-35, 9.04791988e-34]])