In [ ]:
import pandas as pd
import tensorflow as tf
###########################
# 파일로부터 데이터 읽어오기

 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 


In [ ]:
레모네이드

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50

In [ ]:
독립=레모네이드[['온도']]
종속=레모네이드[['판매량']]
X=tf.keras.layers.Input(shape=[1])
Y=tf.keras.layers.Dense(1)(X)

model=tf.keras.models.Model(X,Y)
model.compile(loss='mse')

print(독립.shape)
print(종속.shape)
print(독립)

(6, 1)
(6, 1)
   온도
0  20
1  21
2  22
3  23
4  24
5  25


In [ ]:
model.fit(독립,종속,epochs=1500,verbose=0)

model.predict(독립)

array([[40.058636],
       [42.040787],
       [44.022938],
       [46.00509 ],
       [47.98724 ],
       [49.96939 ]], dtype=float32)

In [ ]:
model.predict([[15]])

array([[20.14783]], dtype=float32)

In [ ]:
보스턴

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [ ]:
독립=보스턴[['crim','zn','indus','chas','nox','rm','age','dis','rad','tax','ptratio','b','lstat']]
종속=보스턴[['medv']]

print(독립.shape,종속.shape)




(506, 13) (506, 1)


In [ ]:
X=tf.keras.layers.Input(shape=[13])
Y=tf.keras.layers.Dense(1)(X)

model=tf.keras.models.Model(X,Y)
model.compile(loss='MSE')




In [ ]:
model.fit(독립,종속,epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.6450
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.3369
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.3210
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 27.0075
Epoch 5/1000
16/16 [==============================] - 0s 2ms/step - loss: 27.1213
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.5480
Epoch 7/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.7036
Epoch 8/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.8708
Epoch 9/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.8351
Epoch 10/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.6596
Epoch 11/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.5566
Epoch 12/1000
16/16 [==============================] - 0s 1ms/step - loss: 27.2795
Epoch 13/1000

In [ ]:
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [ ]:
model.predict(독립[0:5])

array([[29.45359 ],
       [24.33437 ],
       [30.711044],
       [29.67381 ],
       [29.2185  ]], dtype=float32)

In [ ]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [ ]:
model.get_weights()

[array([[-0.08870214],
        [ 0.05763882],
        [-0.0463203 ],
        [ 3.001843  ],
        [ 1.6025598 ],
        [ 4.988053  ],
        [-0.00542816],
        [-0.98632455],
        [ 0.16898797],
        [-0.01052919],
        [-0.2886945 ],
        [ 0.01414465],
        [-0.49447158]], dtype=float32), array([3.4661496], dtype=float32)]

In [ ]:
import pandas as pd
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스=pd.get_dummies(아이리스)

아이리스

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [ ]:
독립=아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속=아이리스[['품종_setosa',	'품종_versicolor'	,'품종_virginica']]

print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [ ]:
X=tf.keras.layers.Input(shape=[4])
Y=tf.keras.layers.Dense(3,activation='softmax')(X)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [ ]:
model.fit(독립,종속,epochs=500)

Epoch 1/500
5/5 [==============================] - 0s 3ms/step - loss: 0.8554 - accuracy: 0.7067
Epoch 2/500
5/5 [==============================] - 0s 4ms/step - loss: 0.8475 - accuracy: 0.7267
Epoch 3/500
5/5 [==============================] - 0s 2ms/step - loss: 0.8417 - accuracy: 0.7267
Epoch 4/500
5/5 [==============================] - 0s 4ms/step - loss: 0.8350 - accuracy: 0.7333
Epoch 5/500
5/5 [==============================] - 0s 3ms/step - loss: 0.8289 - accuracy: 0.7467
Epoch 6/500
5/5 [==============================] - 0s 3ms/step - loss: 0.8221 - accuracy: 0.7600
Epoch 7/500
5/5 [==============================] - 0s 3ms/step - loss: 0.8163 - accuracy: 0.7533
Epoch 8/500
5/5 [==============================] - 0s 3ms/step - loss: 0.8109 - accuracy: 0.7733
Epoch 9/500
5/5 [==============================] - 0s 2ms/step - loss: 0.8044 - accuracy: 0.7600
Epoch 10/500
5/5 [==============================] - 0s 4ms/step - loss: 0.7984 - accuracy: 0.7733
Epoch 11/500
5/5 [===========