In [ ]:
import tensorflow as tf
import pandas as pd

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)

독립=보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속=보스턴[['medv']]

print(독립.shape,종속.shape)




Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
(506, 13) (506, 1)


In [ ]:
##2개의 은닉층 사용
X=tf.keras.layers.Input(shape=[13])
H1=tf.keras.layers.Dense(10,activation='swish')(X)
H2=tf.keras.layers.Dense(1,activation='swish')(H1)
Y=tf.keras.layers.Dense(1)(H2)
model=tf.keras.models.Model(X,Y)
model.compile(loss='mse',metrics='accuracy')




In [ ]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_10 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 11        
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 2         
Total params: 153
Trainable params: 153
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(독립,종속,epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 1ms/step - loss: 20437.6836 - accuracy: 0.0000e+00
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 8391.0400 - accuracy: 0.0000e+00
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 3186.0029 - accuracy: 0.0000e+00
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 921.3688 - accuracy: 0.0000e+00
Epoch 5/1000
16/16 [==============================] - 0s 1ms/step - loss: 255.7872 - accuracy: 0.0000e+00
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 146.1738 - accuracy: 0.0000e+00
Epoch 7/1000
16/16 [==============================] - 0s 1ms/step - loss: 102.5236 - accuracy: 0.0000e+00
Epoch 8/1000
16/16 [==============================] - 0s 1ms/step - loss: 75.9786 - accuracy: 0.0000e+00
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 66.5682 - accuracy: 0.0000e+00
Epoch 10/1000
16/16 [=======================

In [ ]:
print(model.predict(독립[:10]))

[[28.525146]
 [20.923141]
 [29.644278]
 [31.497364]
 [29.455103]
 [26.75813 ]
 [16.860775]
 [17.757381]
 [14.307225]
 [16.452213]]


In [ ]:
print(종속[:10])

   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [ ]:
print(model.get_weights())

[array([[ 2.06590712e-01,  3.92917097e-01, -1.30956280e+00,
        -4.61516887e-01, -3.72185111e-01, -1.97356248e+00,
        -8.20915867e-03, -9.18453261e-02, -3.61789018e-02,
         3.03943038e-01],
       [ 1.83709025e-01, -9.28357542e-02,  1.06503569e-01,
         1.11614347e-01, -1.57991618e-01,  1.50044188e-01,
        -1.05614148e-01, -2.22010776e-01,  5.31062372e-02,
        -3.64843547e-01],
       [ 2.66321063e-01, -1.56068742e-01, -3.83638114e-01,
        -3.61925483e-01,  2.26214111e-01, -2.18297982e+00,
         2.64433064e-02,  3.37095201e-01,  1.62833855e-01,
        -4.48066533e-01],
       [ 8.22003484e-02,  3.31288695e-01,  6.42988086e-01,
         1.30559933e+00,  3.07121873e-02, -8.91664505e-01,
         1.39534330e+00, -1.34951305e+00,  1.43085194e+00,
        -3.12244892e-02],
       [ 4.91765320e-01,  3.60457361e-01, -4.64738309e-01,
        -1.60107151e-01, -4.78930563e-01, -4.17304069e-01,
         1.02628715e-01,  3.66234541e-01, -4.24220383e-01,
         2

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
print(아이리스.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [ ]:
아이리스=pd.get_dummies(아이리스)
독립=아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속=아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [ ]:
X=tf.keras.layers.Input(shape=[4])
H1=tf.keras.layers.Dense(8,activation='swish')(X)
H2=tf.keras.layers.Dense(8,activation='swish')(H1)
H3=tf.keras.layers.Dense(8,activation='swish')(H2)
Y=tf.keras.layers.Dense(3,activation='softmax')(H3)
model=tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [ ]:
model.fit(독립,종속,epochs=200)

Epoch 1/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0851 - accuracy: 0.9733
Epoch 2/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0860 - accuracy: 0.9667
Epoch 3/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0867 - accuracy: 0.9733
Epoch 4/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0923 - accuracy: 0.9533
Epoch 5/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0863 - accuracy: 0.9667
Epoch 6/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0897 - accuracy: 0.9667
Epoch 7/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0840 - accuracy: 0.9667
Epoch 8/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0811 - accuracy: 0.9733
Epoch 9/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0864 - accuracy: 0.9733
Epoch 10/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0849 - accuracy: 0.9733
Epoch 11/200
5/5 [===========

In [ ]:
print(model.predict(독립[:10]))
print(종속[:10])

[[9.99965072e-01 3.49142065e-05 4.09412874e-13]
 [9.99876380e-01 1.23558348e-04 3.13183377e-12]
 [9.99943495e-01 5.65503324e-05 1.71439946e-12]
 [9.99872565e-01 1.27399442e-04 4.22416919e-12]
 [9.99972224e-01 2.77909276e-05 3.48161251e-13]
 [9.99961853e-01 3.81451719e-05 1.06519624e-13]
 [9.99950171e-01 4.98294467e-05 1.09030515e-12]
 [9.99940991e-01 5.89695701e-05 7.98311666e-13]
 [9.99835134e-01 1.64860641e-04 9.95340962e-12]
 [9.99883175e-01 1.16805561e-04 3.02274677e-12]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
5          1              0             0
6          1              0             0
7          1              0             0
8          1              0             0
9          1              0             0
